name: geodask2022a
channels:
  - conda-forge
dependencies:
# dask jupyter base
  - jupyter
  - jupyterlab
  - dask
  - distributed
  - joblib
  - dask-labextension
  - bokeh
  - jupyter-panel-proxy
  - ipywidgets
  # core scipy packages
  - numpy
  - scipy
  - matplotlib-base
  - pandas
  - xarray
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  - xgboost
# NOTE: pangeo-ml image
  # pyviz
  - holoviews
  - panel
  - geoviews
  - hvplot
  - datashader
  - seaborn
  - altair
  - descartes
  - folium
  - vega
  - ipyleaflet
  - leafmap
  # geospatial
  - shapely
  - cartopy
  # - basemap
  - geopandas
  - rasterio
  - netcdf4
  - h5py
  - h5netcdf
  - pytables
  - regionmask
  - rio-cogeo
  - rioxarray
  - geopy
  - h3-py
  # - s2geometry
  - earthpy
  - contextily
  - networkx
  - osmnx
  - owslib
  - pydeck
  - movingpandas
  # geoscience-related
  - gstools
  - pykrige
  - pyinterp
  - xgcm
  # intake-related
  - intake
  - intake-xarray
  - fsspec
  - intake-stac
  - stackstac
  - sentinelsat
  - pystac
  # - sat-stac
  # - sat-search
  - rechunker
  - kerchunk
  - pooch
  - xoak
  - pys2index 
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - xhistogram
  # db stuff
  - psycopg2
  - sqlalchemy
  # misc
  - gcsfs>=0.5.2
  - s3fs
  - google-cloud-storage
  - google-auth
  - google-auth-oauthlib
  - pyarrow
  - fastavro
  - click-plugins
  - click
  - xlrd
  - openpyxl
  - requests
  - toolz
  - streamz
  - tqdm
  - nbconvert
  - papermill
  - sphinx
  - pydata-sphinx-theme
  - sphinx_rtd_theme
  - sphinxcontrib
  - wheel
  - setuptools
  - pip
  - pip:
    - intake_geopandas
    - spotpy
    - rasterstats
    - python-lsp-server
    - pydruid
    - stsci-rtd-theme
    - sphinxcontrib-bibtex
    - pymannkendall
    - mapclassifiy
    - git+https://github.com/manaakiwhenua/rhealpixdggs-py.git@master
    - git+https://github.com/allixender/dggrid4py.git@master
    - git+https://github.com/allixender/utgeo_rtd_theme.git@master
   