name: geodask2022a
channels:
  - conda-forge
dependencies:
  - python>=3.8
# dask jupyter base
  - jupyter
  - jupyterlab
  - dask
  - distributed
  - joblib
  - dask-labextension
  - bokeh
  # - jupyter-panel-proxy
  - ipywidgets
  # core scipy packages
  - numpy=1.21
  - scipy
  - matplotlib-base
  - pandas
  - xarray
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  # pyviz
  - holoviews
  - panel
  - geoviews
  - hvplot
  - datashader
  - seaborn
  - altair
  - folium
  - ipyleaflet
  - leafmap
  - shapely
  - cartopy
  - descartes
  - geopandas
  - rasterio
  - netcdf4
  - h5py
  - h5netcdf
  - pytables
  - regionmask
  - rio-cogeo
  - rioxarray
  - geopy
  - h3-py
  # - s2geometry
  - earthpy
  - contextily
  - networkx
  - osmnx
  - owslib
  - pydeck
  - movingpandas
  # geoscience-related
  - gstools
  - pykrige
  - pyinterp
  - scikit-gstat
  - xarray-spatial
  # intake-related
  - intake
  - intake-xarray
  - fsspec
  - intake-stac
  - stackstac
  - pystac
  - rechunker
  - kerchunk
  - pooch
  - xoak
  - pys2index
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - xhistogram
  # db stuff
  - sqlalchemy
  # misc
  - gcsfs>=0.5.2
  - s3fs
  - pyarrow
  - xlrd
  - openpyxl
  - requests
  - toolz
  - streamz
  - tqdm
  - wheel
  - setuptools
  - pip
  - pip:
    - intake_geopandas
    - spotpy
    - rasterstats
    - pymannkendall
    - mapclassify
    - git+https://github.com/manaakiwhenua/rhealpixdggs-py.git@master
    - git+https://github.com/allixender/dggrid4py.git@master
