name: Repo2Docker Binder Cache
# on: push
on:
  workflow_dispatch:
    inputs:
    
jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - name: git workaround
      run: git config --global --add safe.directory /github/workspace
    - name: Checkout Code
      uses: actions/checkout@main
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "allixender/pangeobinder2022a"
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
